# Generated by Django 4.0.4 on 2022-06-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('state', models.CharField(max_length=50)),
                ('desc_ar', models.TextField()),
                ('currency', models.TextField(choices=[('E', 'Yemen'), ('S', 'Saudi Arabia')], default='E')),
                ('serial_number', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('puyer', models.ManyToManyField(related_name='Puyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ManyToManyField(related_name='Seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhereHouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_where_house', to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('provide', models.ManyToManyField(related_name='providers_product', to='Product.product')),
                ('store', models.ManyToManyField(related_name='store_product_from_providers', to='Product.wherehouses')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWhereHouseRelstions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('whereHouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.wherehouses')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Sigler'), ('P', 'Plorul')], max_length=10)),
                ('count', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_type', to='Product.bills')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Depatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_departments', to='Product.product')),
                ('subDep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_dep', to='Product.depatments')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='providers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_where_house', to='Product.providers'),
        ),
        migrations.AddField(
            model_name='bills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Oprations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeChoice', models.TextField(choices=[('S', 'Seller'), ('B', 'Buyer')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_oprations', to='Product.bills')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_oprations', to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_oprations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product', 'bills')},
            },
        ),
    ]
